//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Need_for_Speed_Underground_Launcher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\EA Games\\Need For Speed Underground\\ISOs")]
        public string NFSU_ISO_Path {
            get {
                return ((string)(this["NFSU_ISO_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NSFU_CD2.iso")]
        public string NFSU_ISO_Filename {
            get {
                return ((string)(this["NFSU_ISO_Filename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\EA Games\\Need For Speed Underground\\")]
        public string NFSU_GameEXE_Path {
            get {
                return ((string)(this["NFSU_GameEXE_Path"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Speed.exe")]
        public string NFSUL_GameEXE_Filename {
            get {
                return ((string)(this["NFSUL_GameEXE_Filename"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NFSUCD2")]
        public string NFSU_ISO_VolumeLabel {
            get {
                return ((string)(this["NFSU_ISO_VolumeLabel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\EA Games\\Need For Speed Underground\\Launcher\\Sounds\\NFSU_M" +
            "enuItemSelect.wav")]
        public string PlayButton_Click_WAV {
            get {
                return ((string)(this["PlayButton_Click_WAV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Program Files (x86)\\EA Games\\Need For Speed Underground\\Launcher\\Sounds\\NFSU_M" +
            "enuItemSelect.wav")]
        public string AboutButton_Click_WAV {
            get {
                return ((string)(this["AboutButton_Click_WAV"]));
            }
        }
    }
}
